import {
  Baby,
  BriefcaseBusiness,
  Building2,
  Car,
  Cat,
  Cpu,
  Drill,
  Gamepad2,
  Home,
  Laptop,
  MonitorSmartphone,
  Shirt,
  Sofa,
  WashingMachine,
} from "lucide-react";
import type {
  Category,
  CategoryTreeNode,
  DashboardMetric,
  Listing,
  Store,
} from "@/types/marketplace";

export const cities = [
  "Bakı",
  "Sumqayıt",
  "Gəncə",
  "Xırdalan",
  "Mingəçevir",
  "Naxçıvan",
  "Abşeron",
  "Ağcabədi",
  "Ağdam",
  "Ağdaş",
  "Ağstafa",
  "Ağsu",
  "Astara",
  "Babək",
  "Balakən",
  "Bərdə",
  "Beyləqan",
  "Biləsuvar",
  "Cəbrayıl",
  "Cəlilabad",
  "Culfa",
  "Daşkəsən",
  "Füzuli",
  "Gədəbəy",
  "Goranboy",
  "Göyçay",
  "Göygöl",
  "Hacıqabul",
  "İmişli",
  "İsmayıllı",
  "Kəlbəcər",
  "Kəngərli",
  "Kürdəmir",
  "Qax",
  "Qazax",
  "Qəbələ",
  "Qobustan",
  "Quba",
  "Qubadlı",
  "Qusar",
  "Laçın",
  "Lerik",
  "Lənkəran",
  "Masallı",
  "Neftçala",
  "Oğuz",
  "Ordubad",
  "Saatlı",
  "Sabirabad",
  "Salyan",
  "Samux",
  "Sədərək",
  "Siyəzən",
  "Şabran",
  "Şamaxı",
  "Şəki",
  "Şəmkir",
  "Şərur",
  "Şirvan",
  "Şuşa",
  "Tərtər",
  "Tovuz",
  "Ucar",
  "Xaçmaz",
  "Xankəndi",
  "Xızı",
  "Xocalı",
  "Xocavənd",
  "Yardımlı",
  "Yevlax",
  "Zaqatala",
  "Zəngilan",
  "Zərdab",
];

export const metroStations = [
  "İçərişəhər",
  "Sahil",
  "28 May",
  "Gənclik",
  "Nəriman Nərimanov",
  "Ulduz",
  "Koroğlu",
  "Qara Qarayev",
  "Neftçilər",
  "Xalqlar Dostluğu",
  "Əhmədli",
  "Həzi Aslanov",
  "Cəfər Cabbarlı",
  "Xətai",
  "Nizami",
  "Elmlər Akademiyası",
  "İnşaatçılar",
  "20 Yanvar",
  "Memar Əcəmi",
  "Nəsimi",
  "Azadlıq prospekti",
  "Dərnəgül",
  "Avtovağzal",
  "8 Noyabr",
  "Xocəsən",
  "Bakmil",
];

export const categories: Category[] = [
  {
    id: "transport",
    name: "Nəqliyyat",
    slug: "neqliyyat",
    icon: Car,
    subcategories: [
      "Avtomobillər",
      "Motosikletlər",
      "Ehtiyat hissələri",
      "Avtobuslar",
      "Yük maşınları",
    ],
    accent: "bg-blue-100 text-blue-700",
  },
  {
    id: "real-estate",
    name: "Daşınmaz əmlak",
    slug: "dasinmaz-emlak",
    icon: Building2,
    subcategories: ["Mənzillər", "Həyət evləri", "Torpaq", "Ofislər", "Obyektlər"],
    accent: "bg-emerald-100 text-emerald-700",
  },
  {
    id: "phones",
    name: "Telefonlar",
    slug: "telefonlar",
    icon: MonitorSmartphone,
    subcategories: ["Apple", "Samsung", "Xiaomi", "Honor", "Digər"],
    accent: "bg-primary-soft text-primary-dark",
  },
  {
    id: "electronics",
    name: "Kompüter və elektronika",
    slug: "komputer-elektronika",
    icon: Laptop,
    subcategories: [
      "Noutbuklar",
      "Masaüstü kompüterlər",
      "Monitorlar",
      "Oyun konsolları",
      "Foto və video",
      "Audio avadanlıq",
    ],
    accent: "bg-cyan-100 text-cyan-700",
  },
  {
    id: "appliances",
    name: "Məişət texnikası",
    slug: "meiset-texnikasi",
    icon: WashingMachine,
    subcategories: ["Soyuducular", "Paltaryuyanlar", "Kondisionerlər", "Mətbəx"],
    accent: "bg-sky-100 text-sky-700",
  },
  {
    id: "home-garden",
    name: "Ev və bağ",
    slug: "ev-bag",
    icon: Sofa,
    subcategories: ["Mebel", "Dekor", "Bağ alətləri", "Təmir"],
    accent: "bg-lime-100 text-lime-700",
  },
  {
    id: "fashion",
    name: "Geyim və moda",
    slug: "geyim-moda",
    icon: Shirt,
    subcategories: ["Qadın geyimi", "Kişi geyimi", "Ayaqqabı", "Aksesuar"],
    accent: "bg-rose-100 text-rose-700",
  },
  {
    id: "kids",
    name: "Uşaq məhsulları",
    slug: "usaq-mehsullari",
    icon: Baby,
    subcategories: ["Oyuncaqlar", "Uşaq arabaları", "Geyim", "Mebel"],
    accent: "bg-orange-100 text-orange-700",
  },
  {
    id: "hobby",
    name: "Hobbi və istirahət",
    slug: "hobbi-istirahet",
    icon: Gamepad2,
    subcategories: ["İdman", "Kitablar", "Musiqi", "Kolleksiya"],
    accent: "bg-indigo-100 text-indigo-700",
  },
  {
    id: "pets",
    name: "Heyvanlar",
    slug: "heyvanlar",
    icon: Cat,
    subcategories: ["İtlər", "Pişiklər", "Quşlar", "Aksesuarlar"],
    accent: "bg-yellow-100 text-yellow-700",
  },
  {
    id: "jobs",
    name: "İş elanları",
    slug: "is-elanlari",
    icon: BriefcaseBusiness,
    subcategories: ["Tam ştat", "Yarım ştat", "Uzaqdan", "Təcrübə"],
    accent: "bg-slate-100 text-slate-700",
  },
  {
    id: "services",
    name: "Xidmətlər",
    slug: "xidmetler",
    icon: Drill,
    subcategories: ["Təmir", "Daşıma", "Təhsil", "Gözəllik"],
    accent: "bg-teal-100 text-teal-700",
  },
  {
    id: "business",
    name: "Biznes və avadanlıq",
    slug: "biznes-avadanliq",
    icon: Cpu,
    subcategories: ["Mağaza avadanlığı", "Ofis", "İstehsalat", "Kassa"],
    accent: "bg-violet-100 text-violet-700",
  },
  {
    id: "other",
    name: "Digər",
    slug: "diger",
    icon: Home,
    subcategories: ["Müxtəlif", "Tapıntılar", "Bağışlanır"],
    accent: "bg-stone-100 text-stone-700",
  },
];

export const categoryTree: CategoryTreeNode[] = [
  {
    id: "electronics",
    name: "Kompüter və elektronika",
    slug: "komputer-elektronika",
    children: [
      {
        id: "audio-video",
        name: "Audio və video",
        slug: "audio-video",
        children: [
          { id: "speakers", name: "Dinamik və sabvuferlər", slug: "dinamik-sabvufer" },
          { id: "headphones", name: "Qulaqlıqlar", slug: "qulaqliqlar" },
          { id: "projectors", name: "Proyektorlar", slug: "proyektorlar" },
          { id: "microphones", name: "Mikrofonlar", slug: "mikrofonlar" },
        ],
      },
      {
        id: "computers",
        name: "Kompüterlər",
        slug: "komputerler",
        children: [
          { id: "laptops", name: "Noutbuklar və netbuklar", slug: "noutbuklar-netbuklar" },
          { id: "desktops", name: "Masaüstü kompüterlər", slug: "masaustu-komputerler" },
          { id: "monitors", name: "Monitorlar", slug: "monitorlar" },
          { id: "components", name: "Komponentlər", slug: "komponentler" },
        ],
      },
      {
        id: "gaming",
        name: "Oyunlar və konsollar",
        slug: "oyunlar-konsollar",
        children: [
          { id: "playstation", name: "PlayStation", slug: "playstation" },
          { id: "xbox", name: "Xbox", slug: "xbox" },
          { id: "controllers", name: "Pultlar və aksesuarlar", slug: "pultlar-aksesuarlar" },
        ],
      },
      { id: "photo-video", name: "Fototexnika", slug: "fototexnika" },
      { id: "smart-watches", name: "Smart saat və qolbaqlar", slug: "smart-saat-qolbaqlar" },
    ],
  },
  {
    id: "home-garden",
    name: "Ev və bağ",
    slug: "ev-bag",
    children: [
      { id: "repair", name: "Təmir və tikinti", slug: "temir-tikinti" },
      {
        id: "furniture",
        name: "Mebellər",
        slug: "mebeller",
        children: [
          { id: "sofas", name: "Divanlar və kreslolar", slug: "divanlar-kreslolar" },
          { id: "beds", name: "Çarpayılar", slug: "carpayilar" },
          { id: "tables", name: "Masalar və oturacaqlar", slug: "masalar-oturacaqlar" },
          { id: "wardrobes", name: "Dolablar və komodlar", slug: "dolablar-komodlar" },
          { id: "kitchen-furniture", name: "Mətbəx mebeli", slug: "metbex-mebeli" },
        ],
      },
      {
        id: "kitchen",
        name: "Qab-qacaq və mətbəx ləvazimatları",
        slug: "metbex-levazimatlari",
        children: [
          { id: "cookware", name: "Qazan və tavalar", slug: "qazan-tavalar" },
          { id: "tableware", name: "Servis dəstləri", slug: "servis-destleri" },
        ],
      },
      { id: "plants", name: "Bitkilər", slug: "bitkiler" },
      { id: "carpets", name: "Xalçalar və aksesuarlar", slug: "xalcalar-aksesuarlar" },
      { id: "garden", name: "Bağ və bostan", slug: "bag-bostan" },
    ],
  },
  {
    id: "transport",
    name: "Nəqliyyat",
    slug: "neqliyyat",
    children: [
      {
        id: "cars",
        name: "Avtomobillər",
        slug: "avtomobiller",
        children: [
          { id: "sedan", name: "Sedan", slug: "sedan" },
          { id: "suv", name: "SUV və krossover", slug: "suv-krossover" },
          { id: "hatchback", name: "Hetçbek", slug: "hetcbek" },
        ],
      },
      {
        id: "water-transport",
        name: "Su nəqliyyatı",
        slug: "su-neqliyyati",
        children: [
          { id: "hydrocycles", name: "Hidrosikllar", slug: "hidrosikllar" },
          { id: "boats", name: "Mühərrikli qayıqlar", slug: "muherrikli-qayiqlar" },
          { id: "yachts", name: "Katerlər və yaxtalar", slug: "katerler-yaxtalar" },
        ],
      },
      { id: "motorcycles", name: "Motosikletlər və mopedlər", slug: "motosikletler-mopedler" },
      { id: "buses", name: "Avtobuslar", slug: "avtobuslar" },
      { id: "trucks", name: "Yük maşınları və qoşqular", slug: "yuk-masinlari-qosqular" },
      { id: "plates", name: "Qeydiyyat nişanları", slug: "qeydiyyat-nisanlari" },
    ],
  },
  {
    id: "phones",
    name: "Telefonlar",
    slug: "telefonlar",
    children: [
      {
        id: "smartphones",
        name: "Smartfonlar",
        slug: "smartfonlar",
        children: [
          { id: "apple", name: "Apple", slug: "apple" },
          { id: "samsung", name: "Samsung", slug: "samsung" },
          { id: "xiaomi", name: "Xiaomi", slug: "xiaomi" },
          { id: "honor", name: "Honor", slug: "honor" },
        ],
      },
      { id: "phone-accessories", name: "Telefon aksesuarları", slug: "telefon-aksesuarlari" },
      { id: "numbers-sim", name: "Nömrələr və SIM-kartlar", slug: "nomreler-sim-kartlar" },
      { id: "repair-parts", name: "Ehtiyat hissələri", slug: "telefon-ehtiyat-hisseleri" },
    ],
  },
  {
    id: "real-estate",
    name: "Daşınmaz əmlak",
    slug: "dasinmaz-emlak",
    children: [
      {
        id: "apartments",
        name: "Mənzillər",
        slug: "menziller",
        children: [
          { id: "new-building", name: "Yeni tikili", slug: "yeni-tikili" },
          { id: "old-building", name: "Köhnə tikili", slug: "kohne-tikili" },
          { id: "daily-rent", name: "Günlük kirayə", slug: "gunluk-kiraye" },
        ],
      },
      { id: "houses", name: "Həyət evləri və villalar", slug: "heyet-evleri-villalar" },
      { id: "land", name: "Torpaq sahələri", slug: "torpaq-saheleri" },
      { id: "offices", name: "Ofislər", slug: "ofisler" },
      { id: "commercial", name: "Obyektlər", slug: "obyektler" },
    ],
  },
  {
    id: "appliances",
    name: "Məişət texnikası",
    slug: "meiset-texnikasi",
    children: [
      { id: "refrigerators", name: "Soyuducular", slug: "soyuducular" },
      { id: "washing-machines", name: "Paltaryuyanlar", slug: "paltaryuyanlar" },
      { id: "conditioners", name: "Kondisionerlər", slug: "kondisionerler" },
      { id: "tv", name: "Televizorlar", slug: "televizorlar" },
      { id: "kitchen-appliances", name: "Mətbəx texnikası", slug: "metbex-texnikasi" },
    ],
  },
  {
    id: "fashion",
    name: "Geyim və moda",
    slug: "geyim-moda",
    children: [
      { id: "women", name: "Qadın geyimi", slug: "qadin-geyimi" },
      { id: "men", name: "Kişi geyimi", slug: "kisi-geyimi" },
      { id: "shoes", name: "Ayaqqabılar", slug: "ayaqqabilar" },
      { id: "accessories", name: "Aksesuarlar", slug: "aksesuarlar" },
      {
        id: "beauty",
        name: "Sağlamlıq və gözəllik",
        slug: "saglamliq-gozellik",
        children: [
          { id: "perfume", name: "Ətriyyat", slug: "etriyyat" },
          { id: "cosmetics", name: "Kosmetika", slug: "kosmetika" },
        ],
      },
    ],
  },
  {
    id: "kids",
    name: "Uşaq məhsulları",
    slug: "usaq-mehsullari",
    children: [
      { id: "toys", name: "Oyuncaqlar", slug: "oyuncaqlar" },
      { id: "strollers", name: "Uşaq arabaları", slug: "usaq-arabalari" },
      { id: "kids-clothes", name: "Uşaq geyimi", slug: "usaq-geyimi" },
      { id: "kids-furniture", name: "Uşaq mebeli", slug: "usaq-mebeli" },
    ],
  },
  {
    id: "hobby",
    name: "Hobbi və istirahət",
    slug: "hobbi-istirahet",
    children: [
      { id: "sport", name: "İdman", slug: "idman" },
      { id: "books", name: "Kitablar", slug: "kitablar" },
      { id: "music", name: "Musiqi alətləri", slug: "musiqi-aletleri" },
      { id: "collectibles", name: "Kolleksiya", slug: "kolleksiya" },
    ],
  },
  {
    id: "pets",
    name: "Heyvanlar",
    slug: "heyvanlar",
    children: [
      { id: "dogs", name: "İtlər", slug: "itler" },
      { id: "cats", name: "Pişiklər", slug: "pisikler" },
      { id: "birds", name: "Quşlar", slug: "quslar" },
      { id: "pet-accessories", name: "Aksesuarlar və yem", slug: "heyvan-aksesuarlari-yem" },
    ],
  },
  {
    id: "jobs",
    name: "İş elanları",
    slug: "is-elanlari",
    children: [
      { id: "full-time", name: "Tam ştat", slug: "tam-stat" },
      { id: "part-time", name: "Yarım ştat", slug: "yarim-stat" },
      { id: "remote", name: "Uzaqdan iş", slug: "uzaqdan-is" },
      { id: "internship", name: "Təcrübə proqramları", slug: "tecrube" },
    ],
  },
  {
    id: "services",
    name: "Xidmətlər",
    slug: "xidmetler",
    children: [
      { id: "repair-services", name: "Təmir", slug: "temir" },
      { id: "delivery-services", name: "Daşıma", slug: "dasima" },
      { id: "education", name: "Təhsil", slug: "tehsil" },
      { id: "beauty-services", name: "Gözəllik xidmətləri", slug: "gozellik-xidmetleri" },
    ],
  },
  {
    id: "business",
    name: "Biznes və avadanlıq",
    slug: "biznes-avadanliq",
    children: [
      { id: "shop-equipment", name: "Mağaza avadanlığı", slug: "magaza-avadanligi" },
      { id: "office-equipment", name: "Ofis avadanlığı", slug: "ofis-avadanligi" },
      { id: "industrial", name: "İstehsalat avadanlığı", slug: "istehsalat-avadanligi" },
      { id: "cash-registers", name: "Kassa və POS", slug: "kassa-pos" },
    ],
  },
  {
    id: "other",
    name: "Digər",
    slug: "diger",
    children: [
      { id: "misc", name: "Müxtəlif", slug: "muxtelif" },
      { id: "lost-found", name: "Tapıntılar", slug: "tapintilar" },
      { id: "giveaway", name: "Bağışlanır", slug: "bagislanir" },
    ],
  },
];

export const listings: Listing[] = [
  {
    id: "lst-001",
    listingNumber: "47078202",
    slug: "iphone-15-pro-max-256gb",
    title: "iPhone 15 Pro Max 256GB, Natural Titanium",
    price: 2190,
    currency: "AZN",
    city: "Bakı",
    district: "Nərimanov",
    date: "2026-07-12",
    category: "Telefonlar",
    subcategory: "Apple",
    condition: "used",
    sellerType: "store",
    sellerId: "usr-1",
    sellerName: "Rauf Məmmədov",
    storeName: "Telefon Dünyası",
    isPremium: true,
    isVip: true,
    delivery: true,
    image:
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1603891128711-11b4b03bb138?auto=format&fit=crop&w=1200&q=80",
    ],
    views: 421,
    favorites: 38,
    phone: "0501234567",
    whatsapp: "994501234567",
    description:
      "Telefon ideal vəziyyətdədir, Face ID, kamera və batareya problemsiz işləyir. Qutu, adapter və zəmanət sənədi var. Mağazadan yoxlayıb ala bilərsiniz.",
    attributes: {
      Marka: "Apple",
      Model: "iPhone 15 Pro Max",
      Yaddaş: "256GB",
      Rəng: "Natural Titanium",
      Zəmanət: "6 ay",
    },
  },
  {
    id: "lst-002",
    listingNumber: "47078203",
    slug: "macbook-air-m3-13-16gb",
    title: "MacBook Air M3 13, 16GB RAM, 512GB SSD",
    price: 2450,
    currency: "AZN",
    city: "Bakı",
    district: "Yasamal",
    date: "2026-07-11",
    category: "Kompüter və elektronika",
    subcategory: "Noutbuklar",
    condition: "new",
    sellerType: "store",
    sellerId: "usr-2",
    sellerName: "Nigar Əliyeva",
    storeName: "Tech Plaza",
    isPremium: true,
    delivery: true,
    image:
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=80",
    ],
    views: 308,
    favorites: 21,
    phone: "0555551200",
    whatsapp: "994555551200",
    description:
      "Rəsmi zəmanətli, bağlı qutuda MacBook Air M3. Tələbələr və iş üçün yüngül, sürətli və səssiz cihazdır.",
    attributes: {
      Prosessor: "Apple M3",
      RAM: "16GB",
      SSD: "512GB",
      Ekran: "13.6 Retina",
    },
  },
  {
    id: "lst-003",
    listingNumber: "47078204",
    slug: "mercedes-c200-2018",
    title: "Mercedes-Benz C 200, 2018 il",
    price: 39800,
    currency: "AZN",
    city: "Gəncə",
    district: "Kəpəz",
    date: "2026-07-10",
    category: "Nəqliyyat",
    subcategory: "Avtomobillər",
    condition: "used",
    sellerType: "individual",
    sellerId: "usr-3",
    sellerName: "Elvin Həsənli",
    isPremium: true,
    delivery: false,
    image:
      "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1200&q=80",
    ],
    views: 928,
    favorites: 65,
    phone: "0707773344",
    whatsapp: "994707773344",
    description:
      "Vuruğu, rəngi yoxdur. Servis tarixçəsi tamdır. Real alıcı ilə qiymətdə razılaşmaq olar.",
    attributes: {
      Marka: "Mercedes-Benz",
      Model: "C 200",
      İl: "2018",
      Yürüş: "82 000 km",
      Yanacaq: "Benzin",
    },
  },
  {
    id: "lst-004",
    listingNumber: "47078205",
    slug: "yasamalda-3-otaqli-menzil",
    title: "Yasamalda yeni tikili 3 otaqlı mənzil",
    price: 226000,
    currency: "AZN",
    city: "Bakı",
    district: "Yasamal",
    date: "2026-07-09",
    category: "Daşınmaz əmlak",
    subcategory: "Mənzillər",
    condition: "used",
    sellerType: "store",
    sellerId: "usr-1",
    sellerName: "Samir Quliyev",
    storeName: "City Home",
    isPremium: false,
    delivery: false,
    image:
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    ],
    views: 519,
    favorites: 42,
    phone: "0513338899",
    whatsapp: "994513338899",
    description:
      "Metroya yaxın, tam təmirli, çıxarışlı mənzil. Kompleksdə parking, mühafizə və həyət var.",
    attributes: {
      Sahə: "102 m²",
      Otaq: "3",
      Mərtəbə: "9/17",
      Çıxarış: "Var",
    },
  },
  {
    id: "lst-005",
    listingNumber: "47078206",
    slug: "samsung-qled-55-smart-tv",
    title: "Samsung QLED 55 Smart TV",
    price: 980,
    currency: "AZN",
    city: "Sumqayıt",
    district: "Mərkəz",
    date: "2026-07-08",
    category: "Məişət texnikası",
    subcategory: "Televizorlar",
    condition: "used",
    sellerType: "individual",
    sellerId: "usr-3",
    sellerName: "Aysel Rəhimova",
    isPremium: false,
    delivery: true,
    image:
      "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=1200&q=80",
    ],
    views: 145,
    favorites: 9,
    phone: "0772221414",
    whatsapp: "994772221414",
    description:
      "Ekranda cızıq yoxdur. Pultu və divar asqısı ilə birlikdə verilir. Smart funksiyaları işləkdir.",
    attributes: {
      Ölçü: "55 düym",
      Panel: "QLED",
      Çözünürlük: "4K",
    },
  },
  {
    id: "lst-006",
    listingNumber: "47078207",
    slug: "ikea-divan-yataq-boz",
    title: "IKEA boz divan-yataq",
    price: 430,
    currency: "AZN",
    city: "Bakı",
    district: "Xətai",
    date: "2026-07-07",
    category: "Ev və bağ",
    subcategory: "Mebel",
    condition: "used",
    sellerType: "individual",
    sellerId: "usr-2",
    sellerName: "Leyla Məlikova",
    isPremium: false,
    delivery: false,
    image:
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80",
    ],
    views: 211,
    favorites: 18,
    phone: "0508886622",
    whatsapp: "994508886622",
    description:
      "Az istifadə olunub, açılıb yataq olur. Parçası təmizdir, ölçüləri kiçik mənzil üçün uyğundur.",
    attributes: {
      Material: "Parça",
      Rəng: "Boz",
      Ölçü: "210x90 sm",
    },
  },
  {
    id: "lst-007",
    listingNumber: "47078208",
    slug: "playstation-5-slim-iki-oyun",
    title: "PlayStation 5 Slim, iki oyunla",
    price: 860,
    currency: "AZN",
    city: "Bakı",
    district: "Binəqədi",
    date: "2026-07-06",
    category: "Hobbi və istirahət",
    subcategory: "Oyun konsolları",
    condition: "used",
    sellerType: "individual",
    sellerId: "usr-1",
    sellerName: "Kamran Vəliyev",
    isPremium: true,
    delivery: true,
    image:
      "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=1200&q=80",
    ],
    views: 372,
    favorites: 29,
    phone: "0994449090",
    whatsapp: "994994449090",
    description:
      "Konsol sakit işləyir, qızma problemi yoxdur. Bir pult, HDMI kabel və iki disk oyun daxildir.",
    attributes: {
      Yaddaş: "1TB",
      Komplekt: "1 pult",
      Zəmanət: "Yoxdur",
    },
  },
  {
    id: "lst-008",
    listingNumber: "47078209",
    slug: "usaq-arabasi-premium",
    title: "Premium uşaq arabası, 3-ü 1-də",
    price: 520,
    currency: "AZN",
    city: "Şəki",
    district: "Mərkəz",
    date: "2026-07-05",
    category: "Uşaq məhsulları",
    subcategory: "Uşaq arabaları",
    condition: "used",
    sellerType: "individual",
    sellerId: "usr-3",
    sellerName: "Günel Abbasova",
    isPremium: false,
    delivery: true,
    image: "/placeholder-stroller.svg",
    images: [
      "/placeholder-stroller.svg",
    ],
    views: 93,
    favorites: 7,
    phone: "0509001122",
    whatsapp: "994509001122",
    description:
      "Yeni kimi qalıb. Avtokreslo, səbət və yağış örtüyü var. Təkərləri rahat hərəkət edir.",
    attributes: {
      Tip: "3-ü 1-də",
      Rəng: "Qara",
      Yaş: "0-36 ay",
    },
  },
];

export const premiumListings = listings.filter((listing) => listing.isPremium);

export const stores: Store[] = [
  {
    id: "store-001",
    name: "Telefon Dünyası",
    slug: "telefon-dunyasi",
    category: "Telefonlar",
    logo: "TD",
    city: "Bakı",
    listingsCount: 128,
    rating: 4.8,
    verified: true,
  },
  {
    id: "store-002",
    name: "Tech Plaza",
    slug: "tech-plaza",
    category: "Elektronika",
    logo: "TP",
    city: "Bakı",
    listingsCount: 86,
    rating: 4.7,
    verified: true,
  },
  {
    id: "store-003",
    name: "City Home",
    slug: "city-home",
    category: "Əmlak",
    logo: "CH",
    city: "Bakı",
    listingsCount: 43,
    rating: 4.6,
    verified: true,
  },
  {
    id: "store-004",
    name: "Baby Market",
    slug: "baby-market",
    category: "Uşaq məhsulları",
    logo: "BM",
    city: "Gəncə",
    listingsCount: 52,
    rating: 4.5,
    verified: true,
  },
  {
    id: "store-005",
    name: "Auto Line",
    slug: "auto-line",
    category: "Nəqliyyat",
    logo: "AL",
    city: "Sumqayıt",
    listingsCount: 31,
    rating: 4.4,
    verified: true,
  },
];

export const dashboardMetrics: DashboardMetric[] = [
  { label: "Ümumi istifadəçi", value: "18 420", delta: "+12.4%" },
  { label: "Aktiv elan", value: "42 108", delta: "+8.1%" },
  { label: "Gözləmədə", value: "316", delta: "-3.2%" },
  { label: "Aylıq gəlir", value: "28 900 AZN", delta: "+18.7%" },
  { label: "Premium elan", value: "2 940", delta: "+9.6%" },
  { label: "Şikayətlər", value: "41", delta: "-11.0%" },
];

export const popularSearches = [
  "iPhone 15",
  "kirayə mənzil",
  "Mercedes C200",
  "PlayStation 5",
  "uşaq arabası",
  "MacBook",
];

export const sellerRatingSummary = {
  rating: 4.9,
  reviews: 126,
  responseTime: "təxminən 12 dəqiqə",
  activeListings: 37,
  joinedAt: "2022-04-18",
  lastSeen: "Bu gün 13:40",
};
